---
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"

- include: configure.yml

- include: monitoring.yml
  when: (monitoring|default('true') and redis_monitoring)
